version: '3'

services:
  db:
    image: postgres:alpine
    restart: on-failure:5
    env_file:
      - ./postgres.env
    volumes:
      - kelepir_db:/tmp/pgdata
    ports:
      - "5432:5432"


volumes:
    kelepir_db: