"""Add version on to id and data_source unique together constraint

Revision ID: 17a457b1b0b3
Revises: b2d256343ab8
Create Date: 2023-05-13 19:41:10.718896

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "17a457b1b0b3"
down_revision = "b2d256343ab8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_house", "houses", type_="unique")
    op.create_unique_constraint(
        "unique_house", "houses", ["internal_id", "data_source", "version"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_house", "houses", type_="unique")
    op.create_unique_constraint(
        "unique_house", "houses", ["internal_id", "data_source"]
    )
    # ### end Alembic commands ###
