"""Add Type and Category fields

Revision ID: 2d15e9e0f2e6
Revises: 2b309be9db26
Create Date: 2023-03-27 01:43:32.476487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from models import ListingCategory, RealtyType



# revision identifiers, used by Alembic.
revision = '2d15e9e0f2e6'
down_revision = '2b309be9db26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    listing_category = postgresql.ENUM('satilik', 'kiralik', name='listing_category')
    listing_category.create(op.get_bind())
    op.add_column('houses', sa.Column('listing_category', listing_category, server_default='satilik', nullable=True))
    realty_type = postgresql.ENUM('daire', 'villa', 'mustakil_ev', 'residence', 'koy_evi', 'ciftlik_evi', 'yazlik', 'prefabrik', 'kosk', 'yali_dairesi', 'yali', name='realty_type')
    realty_type.create(op.get_bind())
    op.add_column('houses', sa.Column('realty_type', realty_type, server_default='daire', nullable=True))
    op.create_index(op.f('ix_houses_listing_category'), 'houses', ['listing_category'], unique=False)
    op.create_index(op.f('ix_houses_realty_type'), 'houses', ['realty_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_houses_realty_type'), table_name='houses')
    op.drop_index(op.f('ix_houses_listing_category'), table_name='houses')
    op.drop_column('houses', 'realty_type')
    op.drop_column('houses', 'listing_category')
    # ### end Alembic commands ###
