"""Remove balcony and parking fields

Revision ID: 4853d21c6211
Revises: e2c751b40a94
Create Date: 2023-04-27 00:17:02.240075

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4853d21c6211"
down_revision = "e2c751b40a94"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("test_houses")
    op.drop_table("test_attributes")
    op.drop_table("test_house_attributes")
    op.drop_index("ix_houses_balcony", table_name="houses")
    op.drop_index("ix_houses_parking", table_name="houses")
    op.drop_column("houses", "balcony")
    op.drop_column("houses", "parking")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "houses", sa.Column("parking", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "houses", sa.Column("balcony", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_index("ix_houses_parking", "houses", ["parking"], unique=False)
    op.create_index("ix_houses_balcony", "houses", ["balcony"], unique=False)
    op.create_table(
        "test_house_attributes",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("house_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("attribute_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "test_attributes",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("value", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "test_houses",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("district", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("city", sa.TEXT(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
