"""Add test tables

Revision ID: 6f61b5a3d9a8
Revises: 4853d21c6211
Create Date: 2023-04-27 17:28:58.524641

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6f61b5a3d9a8"
down_revision = "4853d21c6211"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_house_attributes_attribute_id"),
        "house_attributes",
        ["attribute_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_house_attributes_house_id"),
        "house_attributes",
        ["house_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_house_attributes_house_id"), table_name="house_attributes")
    op.drop_index(
        op.f("ix_house_attributes_attribute_id"), table_name="house_attributes"
    )
    # ### end Alembic commands ###
