"""Add unique together constrait

Revision ID: e2c751b40a94
Revises: 68a1728bca9b
Create Date: 2023-04-06 03:47:14.395329

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e2c751b40a94"
down_revision = "68a1728bca9b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_house", "houses", ["internal_id", "data_source"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_house", "houses", type_="unique")
    # ### end Alembic commands ###
